services:
  mongodb:
    ports:
      - "27017:27017"

  app:
    build:
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run start:dev
    ports:
      - "3000:3000"
    env_file:
      - .env
