services:
  app:
    build: .
    container_name: pokerify_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    depends_on:
      - mongodb
    networks:
      - pokerify_network

  mongodb:
    image: mongo:latest
    container_name: pokerify_db
    hostname: mongodb
    restart: always
    volumes:
      - ./mongodb/initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb-data:/data/db/
      - mongodb-log:/var/log/mongodb/
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - pokerify_network

volumes:
  mongodb-data:
    driver: local
    name: mongo-data
  mongodb-log:
    driver: local
    name: mongo-log

networks:
  pokerify_network:
    name: pokerify_network
    driver: bridge
